name: Connect Numbers deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cache  deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Lint code
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cache  deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install deps
        run: yarn install

      - name: Build App
        run: yarn build